import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalLoader from "@/components/GlobalLoader/GlobalLoader";
import ClientProvider from "@/components/GlobalLoader/ClientProvider";
import { Toaster } from "sonner";
import Auth from "./auth";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalLoader />
        <ClientProvider>
          <Toaster
            richColors
            position="top-right"
            duration={3000}
            closeButton
          />
          <Auth>{children}</Auth>
        </ClientProvider>
      </body>
    </html>
  );
}
